version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - cd web
      - npm install
  pre_build:
    commands:
      - echo Running Tests...
      - cd web
      - npm test
  build:
    commands:
      - echo Building...
      - npm run webpack
artifacts:
  files:
    - web/index.html
    - web/apple-touch-icon.png
    - web/favicon.ico
    - web/favicon-16x16.png
    - web/favicon-32x32.png
    - web/mstile-150x150.png
    - web/safari-pinned-tab.svg
    - web/styles/*
    - web/images/*
    - web/dist/bundle.src
